### ISSUE TITLE
[request] Standalone 4 use with window managers?

### ISSUE THREAD

**Issue by NicTanghe** [qewer33/ClearClock#3]
Any way u Can make this work standalone 4 use with other desktops env`s ? (window managers)

**Comment by qewer33** [comment]
I'm afraid no. That would require me to either rewrite this as a Conky widget or make some sort of a system to display Plasma QML widgets on a standalone application window so it works on all WMs/DEs (which sounds quite challenging since widgets use a lot of Plasma system libraries). Currently don't have the motivation to do either of that but I would be happy if someones makes a Conky widget inspired by this.
